@baseUrl = http://localhost:3003/
@version = v1
@endpoint = simple

### Create =====================================================================
# @name create

POST {{baseUrl}}{{endpoint}} HTTP/1.1
Content-Type: application/json

{
  "data": "{\"email\": \"hey@mail.com\", \"password\": \"101010\", \"post\": [{\"email\": \"hey@mail.com\"}]}",
  "from": "landing"
}

#### Create Response
@id = 61f8d4d88f2231cd65f5d5e8

### Read =======================================================================

GET {{baseUrl}}{{endpoint}}/{{id}} HTTP/1.1
Content-Type: application/json